version: '3.9'

services:
  frontend:
    container_name: sds-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - "PORT=${FRONTEND_PORT}"
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend/:/usr/src/app
      - ignore-fe:/usr/src/app/node_modules
  backend:
    container_name: sds-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    restart: always
    environment:
      - "PORT=${BACKEND_PORT}"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend/:/usr/src/app
      - ignore-be:/usr/src/app/node_modules

volumes:
  ignore-fe: {}
  ignore-be: {}